// data.js
const properties = [
  {
    id: "1",
    slug: "villa-soho-dalmatia",
    title: "Villa SOHO",
    priceTag: "from 280 /daily",
    location: {
      area: "Dalmatia",
      city: "Split",
      country: "Croatia",
    },
    pricePerNight: 620,
    currency: "EUR",
    capacity: {
      guests: 8,
      bedrooms: 6,
      bathrooms: 6,
    },
    gallery: ["./Assets/propery-2.png"],
    booking: { checkIn: "From 4:00 PM", checkOut: "Until 11:00 AM" },
    amenities: [
      "Swimming Pool",
      "WiFi",
      "Air Conditioning",
      "PlayStation",
      "Satellite TV",
      "Microwave",
      "Refrigerator",
      "Oven",
      "Coffee Machine",
      "Parking",
      "Gym",
      "Garden",
    ],
    agent: {
      name: "John Doe",
      phone: "+385 123 456 789",
      email: "villaagent@example.com",
    },
  },
  {
    id: "2",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Makarska",
    priceTag: "From 280 / daily",
    location: {
      area: "Italy",
      city: "Mountain",
      country: "Italy",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/propery-2.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "3",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Roxane",
    priceTag: "from 110 / daily",
    location: {
      area: "Greece",
      city: "Seaside",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-3.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "4",
    slug: "apartment-ikoyi-lagos",
    title: "Aphrodite",
    priceTag: "from 240 /daily",
    location: {
      area: "Greece",
      city: "Seaside",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-4.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "1",
    slug: "apartment-ikoyi-lagos",
    title: "Luxury Apartment Ikoyi",
    priceTag: "from 280/ daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-5.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "6",
    slug: "apartment-ikoyi-lagos",
    title: "Luxury Apartment Ikoyi",
    priceTag: "from 280 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/propert-6.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "7",
    slug: "apartment-ikoyi-lagos",
    title: "Luxury Apartment Ikoyi",
    priceTag: "From 280 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-7.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "8",
    slug: "apartment-ikoyi-lagos",
    title: "Luxury Apartment Ikoyi",
    priceTag: "from 280 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-8.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "9",
    slug: "apartment-ikoyi-lagos",
    title: "Luxury Apartment Ikoyi",
    priceTag: "from 280 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-9.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "10",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Luna",
    priceTag: "from 350 / daily",
    location: {
      area: "Greece",
      city: "Seaside",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 11, bedrooms: 6, bathrooms: 25 },
    gallery: ["./Assets/property-10.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "11",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Tosco",
    priceTag: "from 350 / daily",
    location: {
      area: "Italy",
      city: "mountain",
      country: "Italy",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 4, bedrooms: 2, bathrooms: 2 },
    gallery: ["./Assets/property-11.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "12",
    slug: "apartment-ikoyi-lagos",
    title: "Aphrodite",
    priceTag: "from 350 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 12, bedrooms: 6, bathrooms: 5 },
    gallery: ["./Assets/property-12.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "13",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Makarska",
    priceTag: "from 280 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 8, bedrooms: 8, bathrooms: 4 },
    gallery: ["./Assets/property-13.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "14",
    slug: "apartment-ikoyi-lagos",
    title: "Villa Roxane",
    priceTag: "from 110 / daily",
    location: {
      area: "Greece",
      city: "seaside",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 11, bedrooms: 6, bathrooms: 25 },
    gallery: ["./Assets/property-14.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "15",
    slug: "apartment-ikoyi-lagos",
    title: "Aphrodite",
    priceTag: "from 350 / daily",
    location: {
      area: "Greece",
      city: "Seaside",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 12, bedrooms: 6, bathrooms: 5 },
    gallery: ["./Assets/property-15.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "16",
    slug: "Villa Sunset",
    title: "Luxury Apartment Ikoyi",
    priceTag: "from 280 / daily",
    location: {
      area: "Italy",
      city: "Moutain",
      country: "Italy",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 8, bedrooms: 8, bathrooms: 4 },
    gallery: ["./Assets/property-16.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "17",
    slug: "apartment-ikoyi-lagos",
    title: "White Lady",
    priceTag: "from 110 / daily",
    location: {
      area: "Ikoyi",
      city: "Lagos",
      country: "Nigeria",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 11, bedrooms: 6, bathrooms: 25 },
    gallery: ["./Assets/property-17.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
  {
    id: "18",
    slug: "apartment-ikoyin-lagos",
    title: "Thebes",
    priceTag: "from 240 / daily",
    location: {
      area: "Greece",
      city: "seaside",
      country: "Greece",
    },
    pricePerNight: 300,
    currency: "NGN",
    capacity: { guests: 12, bedrooms: 6, bathrooms: 5 },
    gallery: ["./Assets/property-18.png"],
    booking: { checkIn: "From 2:00 PM", checkOut: "Until 11:00 AM" },
    amenities: ["WiFi", "Air Conditioning", "Parking", "Refrigerator"],
    agent: {
      name: "Chinedu Okafor",
      phone: "+234 801 234 5678",
      email: "ikoyiagent@example.com",
    },
  },
];
